export const KNOWLEDGE_LEVELS = ['SHS1', 'SHS2', 'SHS3'] as const;

export const SHS_SUBJECTS = [
  'English Language',
  'Core Mathematics',
  'Integrated Science',
  'Social Studies',
  'ICT',
  'Computing',
  'Biology',
  'Chemistry',
  'Physics',
  'Elective Mathematics',
  'Additional Mathematics',
  'Financial Accounting',
  'Accounting',
  'Business Management',
  'Economics',
  'Geography',
  'History',
  'Government',
  'Literature in English',
  'French',
  'Spanish',
  'Arabic',
  'Ghanaian Language',
  'Visual Arts',
  'Performing Arts',
  'Art and Design Foundation',
  'Art and Design Studio',
  'Music',
  'Food and Nutrition',
  'Clothing and Textiles',
  'Management in Living',
  'Agricultural Science',
  'Agriculture',
  'Technical Drawing',
  'Physical Education',
  'Physical Education and Health (Core)',
  'Physical Education and Health (Elective)',
  'Religious and Moral Education',
  'Applied Technology',
  'Design and Communication Technology',
  'Engineering',
  'Manufacturing Engineering',
  'Aviation and Aerospace Engineering',
  'Robotics',
  'Biomedical Science',
] as const;

export const KNOWLEDGE_BUCKET = process.env.KNOWLEDGE_BUCKET ?? '';
